linters:
  enable:
    - errcheck
    - errorlint
    - gocritic
    - goimports
    - gosec
    - govet
    - revive
    - staticcheck
    - unparam
    - unused


linters-settings:
  goimports:
    local-prefixes: paper-claw

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
