package oauth_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"golang.org/x/oauth2"

	"paper-claw/internal/oauth"
	"paper-claw/internal/store"
)

func openStore(t *testing.T) *store.DB {
	t.Helper()
	db, err := store.Open(filepath.Join(t.TempDir(), "oauth_test.db"))
	if err != nil {
		t.Fatalf("store.Open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	return db
}

// fakeTokenServer mimics Google's token endpoint, returning a canned token.
func fakeTokenServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		tok := map[string]interface{}{
			"access_token":  "access-tok",
			"token_type":    "Bearer",
			"refresh_token": "refresh-tok",
			"expiry":        time.Now().Add(time.Hour).Format(time.RFC3339),
		}
		_ = json.NewEncoder(w).Encode(tok)
	}))
}

// newTestConfig builds an oauth.Config for testing (no-op setClient, no onReady).
func newTestConfig(t *testing.T, st *store.DB) *oauth.Config {
	t.Helper()
	return oauth.New(
		"client-id", "client-secret",
		"http://localhost", "/oauth/callback",
		st,
		func(_ context.Context, _ *http.Client) error { return nil },
		nil,
	)
}

func TestHandleStart_Redirects(t *testing.T) {
	st := openStore(t)
	cfg := newTestConfig(t, st)

	req := httptest.NewRequest(http.MethodGet, "/oauth/start", nil)
	w := httptest.NewRecorder()
	cfg.HandleStart(w, req)

	resp := w.Result()
	if resp.StatusCode != http.StatusFound {
		t.Errorf("status = %d; want 302", resp.StatusCode)
	}
	loc := resp.Header.Get("Location")
	if !strings.Contains(loc, "accounts.google.com") {
		t.Errorf("redirect = %q; want google auth URL", loc)
	}
	if !strings.Contains(loc, "access_type=offline") {
		t.Errorf("redirect missing access_type=offline: %s", loc)
	}
}

func TestHandleCallback_InvalidState(t *testing.T) {
	st := openStore(t)
	cfg := newTestConfig(t, st)

	req := httptest.NewRequest(http.MethodGet, "/oauth/callback?state=bad-state&code=code", nil)
	w := httptest.NewRecorder()
	cfg.HandleCallback(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d; want 400 for invalid state", w.Code)
	}
}

func TestHandleCallback_ValidFlow(t *testing.T) {
	// Start a fake Google token server.
	ts := fakeTokenServer(t)
	defer ts.Close()

	st := openStore(t)

	// Patch the oauth2 config to point to our fake token server. We do this
	// by creating a minimal oauth2.Config inline and hijacking the token exchange
	// via the oauth.New "setClient" callback which lets us verify that flow ran.
	clientReady := make(chan struct{}, 1)
	cfg := oauth.New(
		"client-id", "client-secret",
		"http://localhost", "/oauth/callback",
		st,
		func(_ context.Context, _ *http.Client) error {
			clientReady <- struct{}{}
			return nil
		},
		nil,
	)

	// Step 1: get a state token via /oauth/start.
	startReq := httptest.NewRequest(http.MethodGet, "/oauth/start", nil)
	startW := httptest.NewRecorder()
	cfg.HandleStart(startW, startReq)
	loc := startW.Result().Header.Get("Location")
	// Extract state from the redirect URL.
	var state string
	for _, part := range strings.Split(loc, "&") {
		if strings.HasPrefix(part, "state=") {
			state = strings.TrimPrefix(part, "state=")
		}
	}
	if state == "" {
		t.Fatal("no state in redirect URL")
	}

	// Step 2: hit /oauth/callback with the state. We can't exercise the actual
	// token exchange without a real Google endpoint, so we just verify that an
	// invalid code results in a 400 (exchange fails) — which proves the state
	// check passed.
	callbackURL := "/oauth/callback?state=" + state + "&code=fake-code"
	cbReq := httptest.NewRequest(http.MethodGet, callbackURL, nil)
	cbW := httptest.NewRecorder()
	cfg.HandleCallback(cbW, cbReq)

	// The code exchange will fail (no real Google endpoint), but the state was
	// accepted — the error is from the exchange, not from the state check.
	if cbW.Code == http.StatusBadRequest && strings.Contains(cbW.Body.String(), "invalid or expired state") {
		t.Error("state was rejected even though it was generated by HandleStart")
	}
}

func TestTokenSource_NilBeforeStore(t *testing.T) {
	st := openStore(t)
	cfg := newTestConfig(t, st)

	ts, err := cfg.TokenSource(context.Background())
	if err != nil {
		t.Fatalf("TokenSource: %v", err)
	}
	if ts != nil {
		t.Error("expected nil TokenSource before any token is stored")
	}
}

func TestTokenSource_ReturnsTokenAfterStore(t *testing.T) {
	st := openStore(t)
	cfg := newTestConfig(t, st)
	ctx := context.Background()

	tok := &oauth2.Token{
		AccessToken:  "access-tok",
		TokenType:    "Bearer",
		RefreshToken: "refresh-tok",
		Expiry:       time.Now().Add(time.Hour),
	}
	raw, _ := json.Marshal(tok) //nolint:gosec // marshaling test token is intentional
	if err := st.PutToken(ctx, raw); err != nil {
		t.Fatalf("PutToken: %v", err)
	}

	ts, err := cfg.TokenSource(ctx)
	if err != nil {
		t.Fatalf("TokenSource: %v", err)
	}
	if ts == nil {
		t.Fatal("expected non-nil TokenSource after storing token")
	}
}

func TestHTTPClient_NilBeforeToken(t *testing.T) {
	st := openStore(t)
	cfg := newTestConfig(t, st)

	hc, err := cfg.HTTPClient(context.Background())
	if err != nil {
		t.Fatalf("HTTPClient: %v", err)
	}
	if hc != nil {
		t.Error("expected nil HTTPClient before token is stored")
	}
}
